config/routes.rb
Rails.application.routes.draw do

  get '/users/sign_up' => 'home_page#home'
  get '/nutriologos/sign_up' => 'home_page#home'
  get '/pacientes/sign_up' => 'home_page#home'

  devise_for :pacientes
  devise_for :nutriologos
  devise_for :users

  resources :sesions
  resources :meta, defaults:{format:'json'}
  resources :documents
  resources :tips_ycomentarios
  resources :dieta
  resources :comments

  mount RailsAdmin::Engine => '/user', as: 'rails_admin'
  get 'static_pages/home'
  get 'nutriologo_pages/mis_sesiones'
  get 'pacientes_pages/mis_sesiones'
  get '/users' => 'user#index', as: :user_root
  get '/admin', to: redirect('/users/sign_in')
  get '/nutriologos' => 'nutriologo_pages#mis_sesiones', as: :nutriologo_root
  get '/pacientes' => 'pacientes_pages#mis_sesiones', as: :paciente_root
  get 'pacientes_pages/programarCita'
  get 'pacientes_pages/ver_metas'
  get '/nutriologo_pages/mis_pacientes'
  get '/pacientes_pages/ver_comentarios'
  get '/pacientes_pages/ver_dietas'



  get '/metas_paciente/:id', to: 'nutriologo_pages#metas_paciente'
  get '/metas_cita/:id', to: 'nutriologo_pages#metas_cita'
  get '/sesiones_paciente/:id', to: 'nutriologo_pages#sesiones_paciente'
  get '/dietas_paciente/:id', to: 'nutriologo_pages#dietas_paciente'

  patch '/cambiar_objetivo/:id', to: 'nutriologo_pages#cambiar_objetivo'

  namespace :user do
    root 'user#index'
  end

  namespace :nutriologo do
    root 'nutriologo_pages#mis_sesiones'
  end

  namespace :paciente do
    root 'pacientes_pages#mis_sesiones'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home_page#home'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :paciente, optional: true, :class_name => 'Paciente'
  belongs_to :nutriologo, optional: true, :class_name => 'Nutriologo'

  validates :title, presence: true
  validates :description, presence: true
end

app/models/dieta.rb
class Dieta < ApplicationRecord
  mount_uploader :dietaPDF, AssetUploader
  validates :dietaPDF, presence: true

  belongs_to :nutriologo
  belongs_to :paciente
end

app/models/document.rb
class Document < ApplicationRecord
  mount_uploader :asset, AssetUploader
  validates :asset, presence: true
end

app/models/horario.rb
class Horario < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/meta.rb
class Meta < ApplicationRecord
end

app/models/nutriologo.rb
class Nutriologo < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sesions, dependent: :destroy
  has_many :dietas

 def email_required?
   false
 end

 def will_save_change_to_email?
   false
 end
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sesions, dependent: :destroy
  has_one :dieta

 def email_required?
   false
 end

 def will_save_change_to_email?
   false
 end
end

app/models/sesion.rb
class Sesion < ApplicationRecord
  belongs_to :paciente
  belongs_to :nutriologo

  validates :hora_id, uniqueness: true
end

app/models/tips_ycomentario.rb
class TipsYcomentario < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :sesions, dependent: :destroy
  has_one :dieta

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end

end

app/controllers/nutriologo_pages_controller.rb
class NutriologoPagesController < ApplicationController

  def metas_paciente
    @paciente = params[:id]
    @ppaciente = Paciente.find_by(id: @paciente)
    @metas = paciente_metas(@paciente)
    @porcentaje = 0
    if @metas.count >0
      @porcentaje = (@metas.where(cumplida: true).count*1.0/(@metas.count*1.0)*100).to_i()
    end
    @comentarios = paciente_tips(@paciente)
  end

  def metas_cita
    @cita = params[:id]
    @metas = cita_metas(@cita)
    @porcentaje = 0
    if @metas.count >0
      @porcentaje = (@metas.where(cumplida: true).count*1.0/(@metas.count*1.0)*100).to_i()
    end

  end

  def sesiones_paciente
    @paciente = params[:id]
    @sesions = paciente_sesions(@paciente)
  end

  def dietas_paciente
    @paciente=params[:id]
    @dietas = paciente_dietas(@paciente)
  end

  def cambiar_objetivo
    if @paciente = Paciente.find_by(id: params[:id])
       if @paciente.update(objetivo: params[:paciente][:objetivo])
       end
    end
    redirect_back(fallback_location: '/nutriologo_pages/mis_pacientes')
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dieta_helper.rb
module DietaHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/meta_helper.rb
module MetaHelper
end

app/helpers/nutriologo_pages_helper.rb
module NutriologoPagesHelper
end

app/helpers/sesions_helper.rb
module SesionsHelper

  def current_user_sesions
    @current_user_sesions ||=
      paciente_sesions(current_user.id).all
  end

  def current_user_next_sessions
    @current_user_next_sessions ||= current_user_sesions.joins("INNER JOIN horarios ON horarios.id = sesions.hora_id").where( ['horarios.hora_disponible >= ?', DateTime.now.getlocal-0.3.day]).order("horarios.hora_disponible asc").all
  end

  def current_user_sesions
    @current_user_sesions ||=
      Sesion.where(nutriologo_id: current_user.id).joins("INNER JOIN horarios ON horarios.id = sesions.hora_id").where( ['horarios.hora_disponible >= ?', DateTime.now.getlocal-1.day]).order("horarios.hora_disponible asc").all
  end

  def current_user_sesionss
    @current_user_sesionss ||=
      Sesion.where(nutriologo_id: current_user.id).joins("INNER JOIN horarios ON horarios.id = sesions.hora_id").where.not( ['horarios.hora_disponible >= ?', DateTime.now.getlocal-1.day]).order("horarios.hora_disponible desc")
  end

  def paciente_metas(paciente_id)
    @paciente_metas =
      Meta.where(paciente_id: paciente_id).order(cumplida: :asc).all
  end

  def cita_metas(cita_id)
    @cita_metas =
      Meta.where(sesions_id: cita_id).all
  end

  def paciente_sesions(paciente_id)
    @paciente_sesions =
      Sesion.where(paciente_id: paciente_id).order(created_at: :asc).all
  end

  def paciente_dietas(paciente_id)
    @paciente_dietas =
      Dieta.where(paciente_id: paciente_id).all
  end

  def current_users_nutriologo
    nutr_sesions = current_user.sesions
    ids_pacientes = []
    nutr_sesions.each do |sesion|
      ids_pacientes.push(sesion.paciente_id)
    end
    ids_pacientes = ids_pacientes.uniq
    pacientes = []
    ids_pacientes.each do |id|
      pacientes.push(Paciente.find(id))
    end
    @current_users_nutriologo ||= pacientes
  end


  def paciente_tips(paciente_id)
    @paciente_tips =
      TipsYcomentario.where(paciente_id: paciente_id).all
  end

  def nutriologo_tips(nutriologo_id)
    @nutriologo_tips =
      TipsYcomentario.where(nutriologo_id: nutriologo_id).all
  end

  def current_user_pesos
    pesos = []
    current_user_sesions.each_with_index do |sesion, index|
      pesos_index = []
      pesos_index.push("Sesion#{index+1}", sesion.peso)
      pesos.push(pesos_index)
    end
    @current_user_pesos ||= pesos
  end

  def current_user_grasa
    grasa = []
    current_user_sesions.each_with_index do |sesion, index|
      grasa_index = []
      grasa_index.push("Sesion#{index+1}", sesion.grasa)
      grasa.push(grasa_index)
    end
    @current_user_grasa ||= grasa

  end

  def current_user_musculo
    musculo = []
    current_user_sesions.each_with_index do |sesion, index|
      musculo_index = []
      musculo_index.push("Sesion#{index+1}", sesion.musculo)
      musculo.push(musculo_index)
    end
    @current_user_musculo ||= musculo
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/user_pages_helper.rb
module UserPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/nutriologo_pages/dietas_paciente.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
        <p class="font-size-title">Dietas</p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
      <div class="card rounded">
        <div class="card-content">
          <p class="card-title">Agregar dietas</p>
          <% @dieta=Dieta.new%>


    <%= form_for (@dieta), :url => dieta_path do |f| %>
      <%= f.label :dietaPDF, "Archivo" %>
      <%= f.file_field :dietaPDF %>
      <%= f.hidden_field :paciente_id, :value => @paciente%>

      <%= f.hidden_field :nutriologo_id, :value => current_nutriologo.id%>

      <%= f.submit "Guardar", class: "btn btn-primary" %>
    <% end %>



<table>
  <thead>
    <tr>
      <th><p>Nutriologo</p></th>
      <th><p>Link</p></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dietas.each do |dieta| %>
      <tr>
        <td><p><%= getNutriologoName(dieta.nutriologo_id) %></p></td>
        <td><p><%= link_to dieta.dietaPDF.file.filename, dieta.dietaPDF.url %></p></td>
        <td><p><%= cl_image_tag(dieta.dietaPDF.file.public_id + ".png",
                                :width => 200, :height => 250, :crop => :fill) %> </p></td>
        <td  style="align:left">
          <div class="row">
            <div class="col s2">
              <%= link_to '<i class="material-icons" style="color: #DC143C;">delete_forever</i>'.html_safe, "/dieta/#{dieta.id}",
                         method: :delete,
                         data: { confirm: '¿Estás seguro?' } %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
      </div>
    </div>
  </div>
</div>

app/views/nutriologo_pages/index.html.erb
<br></br>
<div class="row">
  <div class="col s11 offset-s1">
<h5 class="blue-text text-lighten-3">
      Hola, <%= current_nutriologo.username %>...¿Qué te gustaría consultar el día de hoy?
</h5>

<br></br>

<%= link_to "Mis Sesiones", '/nutriologo_pages/mis_sesiones', class: "btn-large pink darken-1" %>
<%= link_to "Mis Pacientes", '/nutriologo_pages/mis_pacientes', class: "btn-large pink darken-1" %>

</div>
</div>

app/views/nutriologo_pages/metas_cita.html.erb
<% @paciente_id=Sesion.find(@cita).paciente_id%>

<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
        <p class="font-size-title">Metas Paciente <%=getPacienteName(@paciente_id)%></p>
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
          <p class="card-title">Agrega otra meta</p>
  <% @nueva_meta = Meta.new %>
    <%= form_for (@nueva_meta) , :url => meta_path  do |f| %>

    <%= f.text_field :meta%>
    <%= f.hidden_field :paciente_id, :value=> @paciente_id  %>
    <%= f.hidden_field :sesions_id, :value=> @cita  %>
    <%= f.submit "Guardar", class: "btn btn-primary" %>

    <% end %>
    <div class = "row" style="margin-top: 25px;">
    <div class = "col s10 offset-s0 ">
      <p>Avance: <%=@porcentaje%>%</p>
        <div id="progressbar" class="red lighten-2">
          <div class="determinate green accent-4" style="width: <%= @porcentaje%>%"></div>
      </div>
    </div>
    </div>

  <table>
    <thead>
      <tr>
        <th><p>Descripcion</p></th>
        <th><p>Lograda</p></th>
        <th colspan="11"></th>
      </tr>
    </thead>

    <tbody>
      <% @metas.each do |meta| %>
        <tr>
          <td><p><%= meta.meta %></p></td>
          <%if meta.cumplida%>
            <td class= "green darken-1 btn-block center"><p> Completada</p></td>
          <%else%>
            <td class= "red darken-1 btn-block center"><p> En proceso</p></td>
          <%end%>

        </tr>
      <% end %>
    </tbody>
  </table>

  <div class = "row" style="margin-top: 25px;">
  <div class="col s8 m6 l4">
    <%= link_to 'Ver Info Paciente', "/sesiones_paciente/"+@paciente_id.to_s() , class: "col s12 btn btn-primary"%>
  </div>
</div>

app/views/nutriologo_pages/metas_paciente.html.erb
<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
        <p class="font-size-title">Metas y Objetivo del paciente <%=getPacienteName(@paciente)%></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
  <div class = "row">
    <div class = "col">
      <p>Cambia el objetivo del paciente</p>
      <%= form_for (@ppaciente) , :url => '/cambiar_objetivo/'+@paciente.to_s()  do |f| %>
      <%= f.text_field :objetivo%>
      <%= f.submit "Cambiar", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class = "row">
    <div class = "col">
      <p>Agrega otra meta</p>
        <% @nueva_meta = Meta.new %>
        <%= form_for (@nueva_meta) , :url => meta_path  do |f| %>
        <%= f.text_field :meta %>
        <%= f.hidden_field :paciente_id, :value=> @paciente  %>
        <%= f.submit "Guardar", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

<br>
<br>

  <div class = "row">
    <div class = "col s12 m12 l12">
      <p>Avance: <%=@porcentaje%>%</p>
        <div id="progressbar" class="red lighten-2">
          <div class="determinate green accent-4" style="width: <%= @porcentaje%>%"></div>
      </div>
    </div>
  </div>

  <div class = "row">
    <div class = "col s12 m12 l12">
      <div class="flow-text">
        <table style="font-size: 12pt;">
          <thead>
            <tr>
              <th><p>Descripción</p></th>
              <th><p>Actualizar meta</p></th>
              <th><p>Lograda</p></th>
              <th colspan="11"></p></th>
            </tr>
          </thead>
          <tbody>
            <% @metas.each do |meta| %>
              <tr>
                <%= form_for(meta) do |f| %>
                  <td><p><%= f.text_field :meta%></p></td>
                  <td><p><%= f.submit "Guardar", class: "btn btn-primary" %></p></td>
                <% end %>
                <%if meta.cumplida%>
                <td class= "green darken-1 center"> Completada</p></td>
                <%else%>
                <td class= "red darken-1 center"> En proceso</p></td>
                <%end%>
                <td><p><%= link_to 'Eliminar', metum_path(meta), class: "btn btn-primary" ,method: :delete, data: { confirm: '¿Esta seguro?' } %></p></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

<div class="row">
  <div class="col s8 m6 l4">
    <%= link_to 'Ver Info Paciente', "/sesiones_paciente/"+@paciente.to_s() , class: "col s12 btn btn-primary"%>
  </div>
</div>

app/views/nutriologo_pages/mis_pacientes.html.erb
<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
        <p class="font-size-title">Mis Pacientes</p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
  <table>
    <thead>
      <tr>
        <th><p>Paciente</p></th>
        <th colspan="11"><p></p></th>
      </tr>
    </thead>

    <tbody>
      <% current_pacientes_nutriologo.each do |paciente| %>
        <tr>
          <td><p><%= paciente.username %></p></td>
          <% unless paciente.dieta.present? %>
            <td style='text-align: center;'> <i class="material-icons tooltipped" style="color: #ff6961;" data-position="top" data-tooltip="¡El paciente no tiene dieta!">warning</i> </td>
          <% else %>
            <td style='text-align: center;'> <i class="material-icons tooltipped" style="visibility: hidden; color: #ff6961;" data-position="top" data-tooltip="¡El paciente no tiene dieta!">warning</i> </td>
          <% end %>
          <td><%= link_to 'Ver Info Paciente', "/sesiones_paciente/"+paciente.id.to_s(), class: "col s10 btn btn-primary" %></td>
          <td><%= link_to 'Ver Metas y Objetivo Paciente', "/metas_paciente/"+paciente.id.to_s(), class: "col s10 btn btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
      </div>
    </div>
  </div>
</div>

app/views/nutriologo_pages/mis_sesiones.html.erb
<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
        <p class="font-size-title">Mis Sesiones</p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
  <table>
    <thead>
      <tr>
        <th><p>Paciente</p></th>
        <th><p>Sede</p></th>
        <th><p>Fecha</p></th>
        <th colspan="11"><p></p></th>
      </tr>
    </thead>

    <tbody>
      <% current_nutriologo_sesions.each do |sesion| %>
        <% if sesion.active %>
          <tr>
            <td><p><%= getPacienteName(sesion.paciente_id) %></p></td>
            <td><p><%= getSede(sesion.hora_id) %></p></td>
            <td><p><%= getHora(sesion.hora_id) %></p></td>
            <td style='align:left'>
              <div class="row">
                <div class="col s10">
                  <%= link_to 'Ver Info Paciente', "/sesiones_paciente/"+sesion.paciente_id.to_s(), class: "col s10 btn btn-primary" %>
                </div>
                <% if Time.now > Horario.find(sesion.hora_id).hora_disponible %>
                  <div class="col s2"><i class="material-icons tooltipped col s2" style="color: #ad190a;" data-position="top" data-tooltip="¡Ya paso la fecha de la sesión!">warning</i></div>
                <% else %>
                  <div class="col s2"><i class="material-icons tooltipped col s2" style="visibility: hidden; color: #ff6961;" data-position="top" data-tooltip="¡Ya paso la fecha de la sesión!">warning</i></div>
                <% end %>
              </div>
            </td>
            <td></td>
          </tr>
        <% end %>
      <% end %>

      <% current_nutriologo_sesionss.each do |sesion2| %>
      <% if sesion2.active %>
          <tr>
            <td><p><%= getPacienteName(sesion2.paciente_id) %></p></td>
            <td><p><%= getSede(sesion2.hora_id) %></p></td>
            <td><p><%= getHora(sesion2.hora_id) %></p></td>
            <td style='align:left'>
              <div class="row">
                <div class="col s10">
                  <%= link_to 'Ver Info Paciente', "/sesiones_paciente/"+sesion2.paciente_id.to_s(), class: "col s10 btn btn-primary" %>
                </div>
                <% if Time.now > Horario.find(sesion2.hora_id).hora_disponible %>
                  <div class="col s2"><i class="material-icons tooltipped col s2" style="color: #ff6961;" data-position="top" data-tooltip="¡Ya paso la fecha de la sesión!">warning</i></div>
                <% end %>
              </div>
            </td>
            <td></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
      </div>
    </div>
  </div>
</div>

app/views/nutriologo_pages/sesiones_paciente.html.erb
<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
        <p class="font-size-title">Sesiones paciente <%=getPacienteName(@paciente) %></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
  <% numS=1%>
  <table class="centered highlight">
    <thead>
      <tr>
        <th><p>Indicadores</p></th>
        <% @sesions.each do |sesion| %>
          <th><p>Sesión <%=numS%></p></th>
          <% numS+=1%>
        <% end %>
        <% if numS<7
            while numS<7%>
          <th><p>Sesión <%=numS%></p></th>
              <% numS+=1%>
            <%end
           end %>
           <th colspan="11"></th>
        </thead>
        <tbody>
        <tr>
          <td><p>Peso</p></td>
        <% @sesions.each do |sesion| %>
            <td><p><%= sesion.peso %></p></td>
        <% end %>
      </tr>
      <tr>
        <td><p>Estatura</p></td>
      <% @sesions.each do |sesion| %>
          <td><p><%= sesion.estatura %></p></td>
      <% end %>
    </tr>
    <tr>
      <td><p>Grasa</p></td>
    <% @sesions.each do |sesion| %>
        <td><p><%= sesion.grasa %></p></td>
    <% end %>
  </tr>
  <tr>
    <td><p>Músculo</p></td>
  <% @sesions.each do |sesion| %>
      <td><p><%= sesion.musculo %></p></td>
  <% end %>
</tr>
<tr>
  <td><p>Cintura</p></td>
<% @sesions.each do |sesion| %>
    <td><p><%= sesion.cintura %></p></td>
<% end %>
</tr>
<tr>
  <td><p>IMC</p></td>
<% @sesions.each do |sesion| %>
    <td><p><%= sesion.imc %></p></td>
<% end %>
</tr>
<tr>
  <td><p>Grasa Vis</p></td>
<% @sesions.each do |sesion| %>
    <td><p><%= sesion.grasa_vis %></p></td>
<% end %>
</tr>
<tr>
  <td><p>Edad Metabólica</p></td>
<% @sesions.each do |sesion| %>
    <td><p><%= sesion.edad_metabolica %></p></td>
<% end %>
</tr>
<tr>
  <td><p>Hora</p></td>
<% @sesions.each do |sesion| %>
    <td><p><%= getHora(sesion.hora_id) %></p></td>
<% end %>
</tr>
<tr>
  <td><p>Nutriólogo</p></td>
<% @sesions.each do |sesion| %>
    <td><p><%=getNutriologoName(sesion.nutriologo_id) %></p></td>
<% end %>


</tr>
<tr>
  <td><p>Datos</p></td>
<% @sesions.each do |sesion| %>
    <td style="padding-top: 9.3px; padding-bottom: 9.3px;">
      <%=link_to 'Editar datos', edit_sesion_path(sesion), class: "col s12 btn btn-primary" %>
    </p></td>
<% end %>


</tr>
<tr>
  <td><p>Citas</p></td>
<% @sesions.each do |sesion| %>
    <td style="padding-top: 9.3px; padding-bottom: 9.3px;">
      <%=link_to 'Ver Metas Cita', "/metas_cita/"+sesion.id.to_s(), class: "col s12 btn btn-primary"%>
    </p></td>
<% end %>


</tr>

  <td><p>Dietas</p></td>
  <td style="padding-top: 9.3px; padding-bottom: 9.3px;">
    <%= link_to 'Dietas', "/dietas_paciente/"+@paciente.to_s(), class: "col s12 btn btn-primary" %>
  </p></td>

    </tbody>
  </table>
<br>
<br>
<br>
  <div class="row">
  <div class="col s4 offset-s0">
  <%= link_to 'Ver Metas y Objetivo Paciente', "/metas_paciente/"+@paciente.to_s(), class: "btn btn-primary" %>
</div>
</div>
      </div>
    </div>
  </div>
</div>