config/routes.rb
Rails.application.routes.draw do

  get '/users/sign_up' => 'home_page#home'
  get '/nutriologos/sign_up' => 'home_page#home'
  get '/pacientes/sign_up' => 'home_page#home'

  devise_for :pacientes
  devise_for :nutriologos
  devise_for :users

  resources :sesions
  resources :meta, defaults:{format:'json'}
  resources :documents
  resources :tips_ycomentarios
  resources :dieta
  resources :comments

  mount RailsAdmin::Engine => '/user', as: 'rails_admin'
  get 'static_pages/home'
  get 'nutriologo_pages/mis_sesiones'
  get 'pacientes_pages/mis_sesiones'
  get '/users' => 'user#index', as: :user_root
  get '/admin', to: redirect('/users/sign_in')
  get '/nutriologos' => 'nutriologo_pages#mis_sesiones', as: :nutriologo_root
  get '/pacientes' => 'pacientes_pages#mis_sesiones', as: :paciente_root
  get 'pacientes_pages/programarCita'
  get 'pacientes_pages/ver_metas'
  get '/nutriologo_pages/mis_pacientes'
  get '/pacientes_pages/ver_comentarios'
  get '/pacientes_pages/ver_dietas'



  get '/metas_paciente/:id', to: 'nutriologo_pages#metas_paciente'
  get '/metas_cita/:id', to: 'nutriologo_pages#metas_cita'
  get '/sesiones_paciente/:id', to: 'nutriologo_pages#sesiones_paciente'
  get '/dietas_paciente/:id', to: 'nutriologo_pages#dietas_paciente'

  patch '/cambiar_objetivo/:id', to: 'nutriologo_pages#cambiar_objetivo'

  namespace :user do
    root 'user#index'
  end

  namespace :nutriologo do
    root 'nutriologo_pages#mis_sesiones'
  end

  namespace :paciente do
    root 'pacientes_pages#mis_sesiones'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home_page#home'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :paciente, optional: true, :class_name => 'Paciente'
  belongs_to :nutriologo, optional: true, :class_name => 'Nutriologo'

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:destroy, :edit, :update]
	layout :set_layout

  def index
    if current_paciente != nil
      @comments = Comment.where(paciente: current_paciente).all
    else
      @comments = Comment.where(nutriologo: current_nutriologo).all
    end
  end

  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to request.referrer
  end

  def update
    if current_paciente != nil
      user = current_paciente
    end

    if current_nutriologo != nil
      user = current_nutriologo
    end

    if @comment.paciente == user || @comment.nutriologo == user
      if @comment.update(comment_params)
        redirect_to comments_path
      else
        render 'edit'
      end
    end
  end

  def create
    @comment= Comment.new(comment_params)

    if current_paciente != nil
      @comment.paciente = current_paciente
    end

    if current_nutriologo != nil
      @comment.nutriologo = current_nutriologo
    end

    if @comment.save
      redirect_to comments_path
		else
			render 'new'
    end
  end

  private
  # Sets layout depending on user
    def set_layout
      if current_paciente != nil
        "pacientes_pages"
      else
        "nutriologo_pages"
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :description)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<div class="card rounded" style="width: 90%; margin: auto; text-align='center'">
  <div class="card-content">
  	<div class = "row">
  		<div class = "col">
  			<p class="font-size-title">Editar comentario</p>
  			<%= form_for (@comment) do |f| %>
  			<%= f.label :title %>
  			<%= f.text_field :title %>
  			<%= f.label :description %>
  			<%= f.text_field :description %>
  			<%= f.submit "Actualizar comentario", class: "btn btn-primary" %>
  			<% end %>
  		</div>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<div class="card rounded" style="width: 90%; margin: auto; text-align='center'">
  <div class="card-content">
    <div class = "row">
      <div class = "col s12 m12 l12">
        <div class="flow-text">
          <table style="font-size: 12pt;">
            <thead>
              <tr>
                <th><p>Título</p></th>
                <th><p>Descripción</p></th>
                <th><p>Autor</p></th>
                <th colspan="11"></th>
              </tr>
            </thead>
            <tbody>
              <% @comments.each do |comment| %>
                <tr style="word-wrap: break-word;">
                  <td><p><%= comment.title %></p></td>
                  <td><p><%= comment.description %></p></td>
                  <% if comment.paciente != nil %>
                    <td><p><%= comment.paciente.username %></p></td>
                  <% else %>
                    <td><p><%= comment.nutriologo.username %></p></td>
                  <% end %>
                  <td class="center">
                    <p>
                    <%= link_to edit_comment_path(comment) do %>
                      <i class="material-icons black-text">create</i>
                    <% end %>
                    </p>
                  </td>
                  <td class="center">
                    <p>
                    <%= link_to comment_path(comment), method: :delete, data: { confirm: '¿Esta seguro?' } do %>
                      <i class="material-icons red-text">delete</i>
                    <% end %>
                    </p>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="card-action rounded-25">
    <%= link_to 'Nuevo Comentario', new_comment_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="card rounded" style="width: 90%; margin: auto; text-align='center'">
  <div class="card-content">
  	<div class = "row">
  		<div class = "col">
  			<p class="font-size-title">Nuevo comentario</p>
  			<%= form_for (@comment) do |f| %>
  			<%= f.label :title %>
  			<%= f.text_field :title %>
  			<%= f.label :description %>
  			<%= f.text_field :description %>
  			<%= f.submit "Crear comentario", class: "btn btn-primary" %>
  			<% end %>
      </div>
    </div>
	</div>
</div>