config/routes.rb
Rails.application.routes.draw do

  get '/users/sign_up' => 'home_page#home'
  get '/nutriologos/sign_up' => 'home_page#home'
  get '/pacientes/sign_up' => 'home_page#home'

  devise_for :pacientes
  devise_for :nutriologos
  devise_for :users

  resources :sesions
  resources :meta, defaults:{format:'json'}
  resources :documents
  resources :tips_ycomentarios
  resources :dieta
  resources :comments

  mount RailsAdmin::Engine => '/user', as: 'rails_admin'
  get 'static_pages/home'
  get 'nutriologo_pages/mis_sesiones'
  get 'pacientes_pages/mis_sesiones'
  get '/users' => 'user#index', as: :user_root
  get '/admin', to: redirect('/users/sign_in')
  get '/nutriologos' => 'nutriologo_pages#mis_sesiones', as: :nutriologo_root
  get '/pacientes' => 'pacientes_pages#mis_sesiones', as: :paciente_root
  get 'pacientes_pages/programarCita'
  get 'pacientes_pages/ver_metas'
  get '/nutriologo_pages/mis_pacientes'
  get '/pacientes_pages/ver_comentarios'
  get '/pacientes_pages/ver_dietas'



  get '/metas_paciente/:id', to: 'nutriologo_pages#metas_paciente'
  get '/metas_cita/:id', to: 'nutriologo_pages#metas_cita'
  get '/sesiones_paciente/:id', to: 'nutriologo_pages#sesiones_paciente'
  get '/dietas_paciente/:id', to: 'nutriologo_pages#dietas_paciente'

  patch '/cambiar_objetivo/:id', to: 'nutriologo_pages#cambiar_objetivo'

  namespace :user do
    root 'user#index'
  end

  namespace :nutriologo do
    root 'nutriologo_pages#mis_sesiones'
  end

  namespace :paciente do
    root 'pacientes_pages#mis_sesiones'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home_page#home'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :paciente, optional: true, :class_name => 'Paciente'
  belongs_to :nutriologo, optional: true, :class_name => 'Nutriologo'

  validates :title, presence: true
  validates :description, presence: true
end

app/models/dieta.rb
class Dieta < ApplicationRecord
  mount_uploader :dietaPDF, AssetUploader
  validates :dietaPDF, presence: true

  belongs_to :nutriologo
  belongs_to :paciente
end

app/models/document.rb
class Document < ApplicationRecord
  mount_uploader :asset, AssetUploader
  validates :asset, presence: true
end

app/models/horario.rb
class Horario < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/meta.rb
class Meta < ApplicationRecord
end

app/models/nutriologo.rb
class Nutriologo < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sesions, dependent: :destroy
  has_many :dietas

 def email_required?
   false
 end

 def will_save_change_to_email?
   false
 end
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sesions, dependent: :destroy
  has_one :dieta

 def email_required?
   false
 end

 def will_save_change_to_email?
   false
 end
end

app/models/sesion.rb
class Sesion < ApplicationRecord
  belongs_to :paciente
  belongs_to :nutriologo

  validates :hora_id, uniqueness: true
end

app/models/tips_ycomentario.rb
class TipsYcomentario < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :sesions, dependent: :destroy
  has_one :dieta

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end

end

app/controllers/pacientes_pages_controller.rb
class PacientesPagesController < ApplicationController

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dieta_helper.rb
module DietaHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/meta_helper.rb
module MetaHelper
end

app/helpers/pacientes_pages_helper.rb
module PacientesPagesHelper
end

app/helpers/sesions_helper.rb
module SesionsHelper

  def current_user_sesions
    @current_user_sesions ||=
      paciente_sesions(current_user.id).all
  end

  def current_user_next_sessions
    @current_user_next_sessions ||= current_user_sesions.joins("INNER JOIN horarios ON horarios.id = sesions.hora_id").where( ['horarios.hora_disponible >= ?', DateTime.now.getlocal-0.3.day]).order("horarios.hora_disponible asc").all
  end

  def current_user_sesions
    @current_user_sesions ||=
      Sesion.where(nutriologo_id: current_user.id).joins("INNER JOIN horarios ON horarios.id = sesions.hora_id").where( ['horarios.hora_disponible >= ?', DateTime.now.getlocal-1.day]).order("horarios.hora_disponible asc").all
  end

  def current_user_sesionss
    @current_user_sesionss ||=
      Sesion.where(nutriologo_id: current_user.id).joins("INNER JOIN horarios ON horarios.id = sesions.hora_id").where.not( ['horarios.hora_disponible >= ?', DateTime.now.getlocal-1.day]).order("horarios.hora_disponible desc")
  end

  def paciente_metas(paciente_id)
    @paciente_metas =
      Meta.where(paciente_id: paciente_id).order(cumplida: :asc).all
  end

  def cita_metas(cita_id)
    @cita_metas =
      Meta.where(sesions_id: cita_id).all
  end

  def paciente_sesions(paciente_id)
    @paciente_sesions =
      Sesion.where(paciente_id: paciente_id).order(created_at: :asc).all
  end

  def paciente_dietas(paciente_id)
    @paciente_dietas =
      Dieta.where(paciente_id: paciente_id).all
  end

  def current_users_nutriologo
    nutr_sesions = current_user.sesions
    ids_pacientes = []
    nutr_sesions.each do |sesion|
      ids_pacientes.push(sesion.paciente_id)
    end
    ids_pacientes = ids_pacientes.uniq
    pacientes = []
    ids_pacientes.each do |id|
      pacientes.push(Paciente.find(id))
    end
    @current_users_nutriologo ||= pacientes
  end


  def paciente_tips(paciente_id)
    @paciente_tips =
      TipsYcomentario.where(paciente_id: paciente_id).all
  end

  def nutriologo_tips(nutriologo_id)
    @nutriologo_tips =
      TipsYcomentario.where(nutriologo_id: nutriologo_id).all
  end

  def current_user_pesos
    pesos = []
    current_user_sesions.each_with_index do |sesion, index|
      pesos_index = []
      pesos_index.push("Sesion#{index+1}", sesion.peso)
      pesos.push(pesos_index)
    end
    @current_user_pesos ||= pesos
  end

  def current_user_grasa
    grasa = []
    current_user_sesions.each_with_index do |sesion, index|
      grasa_index = []
      grasa_index.push("Sesion#{index+1}", sesion.grasa)
      grasa.push(grasa_index)
    end
    @current_user_grasa ||= grasa

  end

  def current_user_musculo
    musculo = []
    current_user_sesions.each_with_index do |sesion, index|
      musculo_index = []
      musculo_index.push("Sesion#{index+1}", sesion.musculo)
      musculo.push(musculo_index)
    end
    @current_user_musculo ||= musculo
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/user_pages_helper.rb
module UserPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pacientes_pages/index.html.erb
<br><br>
<div class="row">
  <div class="col s10 offset-s1">
    <h4 class="grey-text text-darken-3">
      Hola <%= current_user.username %>...¿Qué sección quieres revisar hoy?
    </h4>

    <br><br>

    <div class="row">
      <div class="col s8 m6 l4 offset-s2 offset-m3 offset-l2">
        <div class="card-panel white">
          <img src="<%= asset_path('miPerfilResize.jpg') %>" height="100%" width="100%"/>
          <%= link_to "Mi Perfil", '/pacientes_pages/mis_sesiones', class: "btn-large pink darken-1 btn-block"%>
        </div>
      </div>

      <div class="col s8 m6 l4 offset-s2 offset-m3">
        <div class="card-panel white">
          <img src="<%= asset_path('menuSemanalProxResize.jpg') %>" height="100%" width="100%"/>
          <%= link_to "Menú Semanal", '/menusemanal', class: "btn-large pink darken-1 btn-block disabled" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pacientes_pages/mis_sesiones.html.erb
<meta name = "viewport" content = "width = device-width, initial-scale = 1">
<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
        <p class="font-size-title">Hola <%= current_paciente.username %>, tu plan es <%=current_paciente.objetivo%> y estos son tus datos:</p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s2">
      <div class="card rounded">
        <div class="card-content">
          <p class="card-title">Datos Iniciales</p>
        <%if current_paciente_sesions.first != nil%>
          <table class="responsive-table centered highlight">
            <thead>
            </thead>
            <tbody>
              <tr>
                <td><p>Peso: <%= current_paciente_sesions.first.peso %> kg.</p></td>
              </tr>
              <tr>
                <td><p>Estatura: <%= current_paciente_sesions.first.estatura %> m.</p></td>
              </tr>
              <tr>
                <td><p>Grasa: <%= current_paciente_sesions.first.grasa %>%</p></td>
              </tr>
              <tr>
                <td><p>Músculo: <%= current_paciente_sesions.first.musculo %>%</p></td>
              </tr>
              <tr>
                <td><p>Cintura: <%= current_paciente_sesions.first.cintura %> cm.</p></td>
              </tr>
              <tr>
                <td><p>IMC: <%= current_paciente_sesions.first.imc %></p></td>
              </tr>
              <tr>
                <td><p>G.V.:<%= current_paciente_sesions.first.grasa_vis %></p></td>
              </tr>
              <tr>
                <td><p>E.M.: <%= current_paciente_sesions.first.edad_metabolica %></p></td>
              </tr>
            </tbody>
          </table>

          <div class ="row" style="margin-top: 15px">
            <div class="col s12">
              <p class="grey-text text-darken-1 font-size-small">*IMC: Índice de Masa Corporal</p>
            </div>
            <div class="col s12" class="flow-text">
              <p class="grey-text text-darken-1 font-size-small">*GV: Grasa Visceral</p>
            </div>
            <div class="col s12" class="flow-text">
              <p class="grey-text text-darken-1 font-size-small">*EM: Edad Metabólica</p>
            </div>
          </div>
        <% else %>
          <div class ="row">
            <div class="col s10 offset-s1 card-panel blue lighten-4">
              <p>Por el momento no tienes información</p>
            </div>
          </div>
        <% end %>
          </div>
        </div>
      </div>


      <div class="col s10">
        <div class="row">
          <div class="col s12">
            <div class="card rounded">
            <div class="card-content">
              <p class="card-title">Seguimiento</p>
              <table class="responsive-table centered highlight" style="font-size: 12pt;">
                <thead>
                  <tr>
                    <th><p>Número Sesión</p></th>
                    <th><p>Peso</p></th>
                    <th><p>Estatura</p></th>
                    <th><p>Grasa</p></th>
                    <th><p>Músculo</p></th>
                    <th><p>Cintura</p></th>
                    <th><p>IMC</p></th>
                    <th><p>G.V.</p></th>
                    <th><p>E.M.</p></th>
                    <th><p>Hora</p></th>
                    <th><p>Nutriólogo</p></th>
                    <th colspan="11"></th>
                  </tr>
                </thead>
                <% numS=1%>
                <tbody>
                  <% current_paciente_sesions.each do |sesion| %>

                    <tr>
                      <td><p><%=numS%></p></td>
                      <td><p><%= sesion.peso %>kg</p></td>
                      <td><p><%= sesion.estatura %>m</p></td>
                      <td><p><%= sesion.grasa %>%</p></td>
                      <td><p><%= sesion.musculo %>%</p></td>
                      <td><p><%= sesion.cintura %>cm</p></td>
                      <td><p><%= sesion.imc %></p></td>
                      <td><p><%= sesion.grasa_vis %></p></td>
                      <td><p><%= sesion.edad_metabolica %></p></td>
                      <td><p><%= getDia(sesion.hora_id) %></p></td>
                      <td><p><%=getNutriologoName(sesion.nutriologo_id)%></p></td>
                    </tr>
                    <% numS+=1%>
                  <% end %>
                </tbody>
              </table>
          </div>
        </div>
      </div>

      <div class="col s12">
        <div class="card rounded">
          <div class="card-content">
            <p class="card-title">Historial</p>
            <div class="row">
              <div class = "col s4">
                <div class="row">
                  <div class="col s12">
                    <p>Historial de Peso</p>
                  </div>
                </div>

                <div class="row">
                  <div class="col s12">
                    <%= line_chart current_paciente_pesos %>
                  </div>
                </div>
              </div>

              <div class = "col s4">
                <div class="row">
                  <div class="col s12">
                    <p>Historial de % de Grasa</p>
                  </div>
                </div>

                <div class="row">
                  <div class="col s12">
                    <%= line_chart current_paciente_grasa %>
                  </div>
                </div>
              </div>

              <div class = "col s4">
                <div class="row">
                  <div class="col s12">
                    <p>Historial de % de Músculo</p>
                  </div>
                </div>

                <div class="row">
                  <div class="col s12">
                    <%= line_chart current_paciente_musculo %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pacientes_pages/ver_comentarios.html.erb
<div class="card" style="width: 90%; margin: auto; text-align="center">
<h1>Tips y Comentarios</h1>


    <% paciente_tips(current_user.id).each do |tip| %>


        <%= tip.tip%><br>
        Atte: <br>
        <%= tip.remitente %><br><br>

    <% end %>


                                                                      <br></br>
                                                                      </div>

app/views/pacientes_pages/ver_dietas.html.erb
<div class ="row">
  <div class="col s10 offset-s1 blue lighten-4">
    <p class="font-size-title">No tienes ninguna dieta asignada.</p>
  </div>
</div>

app/views/pacientes_pages/ver_metas.html.erb
<%@metas = paciente_metas(current_paciente.id)%>
<% @porcentaje = 0
  if @metas.count >0
    @porcentaje = (@metas.where(cumplida: true).count*1.0/(@metas.count*1.0)*100).to_i()
  end
%>

<div class="row">
  <div class="col s12">
    <div class="card rounded" style="margin: auto; text-align='center'">
      <div class="card-content">
        <div class="row">
          <div class="col s12">
            <p class="font-size-title">Estas son tus metas <%=current_paciente.username%>, ¡¡Ánimo!!</p>
          </div>
        </div>

        <div class="row">
          <div class="col s10 offset-s1">
            <p>Llevas <%=@porcentaje%>% completado</p>
          </div>

          <div class="col s10 offset-s1">
            <div id="progressbar" class = "teal lighten-4">
              <div class="determinate light-green accent-4" style="width: <%= @porcentaje%>%"></div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col s12">
            <% @metas.each do |meta| %>
              <div class = "row">
                <div class = "col s10 offset-s1 ">
                  <div class="card rounded">
                    <%= form_for(meta) do |f| %>
                      <div class="card-content">
                        <label>
                          <%= f.check_box :cumplida %>
                          <span><p><%=meta.meta%></p>&nbsp&nbsp&nbsp&nbsp</span>
                        </label>
                      </div>

                      <div class="card-action">
                        <%= f.submit "Guardar", class: "btn btn-primary" %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>